FROM ckan/ckan-base:2.11.4

RUN pip install --no-cache-dir \
    ckanext-hierarchy \
    ckanext-dcat \
    ckanext-scheming \
    "git+https://github.com/ckan/ckanext-spatial.git#egg=ckanext-spatial"